# Generated by Django 6.0.5 on 2026-07-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('position', models.CharField(choices=[('header_top', 'Header top'), ('home_top', 'Home top'), ('below_hero', 'Below hero'), ('in_feed', 'Inside news feed'), ('category_top', 'Category top'), ('article_top', 'Article top'), ('article_middle', 'Article middle'), ('article_sidebar', 'Article sidebar'), ('footer_top', 'Footer top')], max_length=40)),
                ('ad_type', models.CharField(choices=[('image', 'Image ad'), ('html', 'HTML/script ad'), ('text', 'Text ad')], default='image', max_length=20)),
                ('sponsor_name', models.CharField(blank=True, max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements')),
                ('target_url', models.URLField(blank=True)),
                ('text', models.CharField(blank=True, max_length=240)),
                ('html_code', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('internal_note', models.CharField(blank=True, max_length=220)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'advertisement',
                'ordering': ['position', 'display_order', '-created_at'],
            },
        ),
    ]
