# Generated by Django 6.0.5 on 2026-07-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('header_top', 'Header top'), ('home_top', 'Home top'), ('below_hero', 'Below hero'), ('after_visual_deck', 'After visual stories'), ('in_feed', 'Inside news feed'), ('latest_bottom', 'Below latest news'), ('category_section', 'Between homepage categories'), ('category_top', 'Category top'), ('category_in_feed', 'Inside category feed'), ('category_bottom', 'Category bottom'), ('article_top', 'Article top'), ('article_after_image', 'Article after image'), ('article_middle', 'Article middle'), ('article_sidebar', 'Article sidebar'), ('article_related_bottom', 'Article related bottom'), ('footer_top', 'Footer top')], max_length=40),
        ),
    ]
