# Generated by Django 6.0.5 on 2026-07-01 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_advertisement_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='button_text',
            field=models.CharField(default='Call Now', max_length=40),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='subtitle',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
