# Generated by Django 6.0.5 on 2026-07-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_advertisement_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='background_color',
            field=models.CharField(default='#fff9ea', max_length=40),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='background_color_2',
            field=models.CharField(default='#fff3f0', max_length=40),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='badge_bg_color',
            field=models.CharField(default='#111827', max_length=40),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='badge_text_color',
            field=models.CharField(default='#ffffff', max_length=40),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='border_color',
            field=models.CharField(default='#cf202f', max_length=40),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='button_bg_color',
            field=models.CharField(default='#c91f2b', max_length=40),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='button_text_color',
            field=models.CharField(default='#ffffff', max_length=40),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='contact_text_color',
            field=models.CharField(default='#941023', max_length=40),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='sponsor_text_color',
            field=models.CharField(default='#4b5563', max_length=40),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='subtitle_color',
            field=models.CharField(default='#4b5563', max_length=40),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title_color',
            field=models.CharField(default='#07111f', max_length=40),
        ),
    ]
